### ISSUE TITLE
Сделать увеличение количества на фронте

### ISSUE THREAD

**Issue by goxa87** [SergeyV17/InternetShop#1]
как бы не имеет смысл для каждого нажатия увеличивать на 1 через запрос  потомучто будет  обновление формы и состояние объектов на сервере не сохраняется. 

примено так. 
на фронте ванильным js или jq увеличиваешь значение инпута на 1, а потом на сабмите формы это значение передаешь на сервер

**Comment by SergeyV17** [comment]
Согласен с замечанием, сам гуглил как подобное сделать, но быстрого решения не нашёл. Когда буду сдавать модули по асп, попробую доработать по уму, пока что с js и jq не знаком.

**Comment by goxa87** [comment]
jq это очень быстрое и простое в изучение. на метаните у меня заняло пару вечеров изучение
